### ISSUE TITLE
"Invalid variable attributes" displayed in variables lists for Lua 5.1 // lrdb plugin version >0.3.4

### ISSUE THREAD

**Issue by gossidog** [satoren/vscode-lrdb#91]
Issue Type: <b>Bug</b>

I use lrdb to remote-debug an application that has lua 5.1 embedded. This worked very nicely up until satoren.lrdb extension version 0.4.0, after which significant issues with the variables lists shown in vscode were observed.

Some test script being debugged with satoren.lrdb extension version 0.4.0 (note that 1.0.0 behaves the same):
![test_script_0 4 0](https://user-images.githubusercontent.com/46304888/154484412-042113b0-61a7-4e38-a3b8-06e48cb8c8f7.png)

The same script being debugged with satoren.lrdb extension version 0.3.4:
![test_script_0 3 4](https://user-images.githubusercontent.com/46304888/154484450-a4e9de0b-6887-47e1-9811-a9a8dfab95ce.png)

I had a go at trying to get to the root of this issue - swapping bits of extension script from version 0.3.4 in to version 0.4.0, but the refactor that has taken place is significant and my complete lack of knowledge of javascript, vscode plugin debugging or the debug adapter protocol forced me to abandon the attempt.

I can roll back to version 0.3.4 of the extension, but obviously it would better to fix the issue somehow. Let me know if I can provide any further information to help fix this issue.

Extension version: 0.4.0
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by satoren** [comment]
Thank you for report.
I was able to reproduce it and will fix it.
